default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: blueheronvideo_development

test:
  <<: *default
  database: blueheronvideo_test

production:
  <<: *default
  database: blueheronvideo_production
  username: blueheronvideo
  password: <%= ENV['BLUEHERONVIDEO_DATABASE_PASSWORD'] %>
